baseURL = "https://mzegar.github.io/"
languageCode = "en-us"
theme = "reloaded"
title = "Matthew Zegar | Personal Website"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.highlight]
            style = 'monokai'

[menu]
    [[menu.main]]
        name = "Projects"
        url = "/projects/"
        weight = 1
    [[menu.main]]
        name = "Posts"
        url = "/posts/"
        weight = 2
