# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Reloaded"
license = "MIT"
licenselink = "https://github.com/mzegar/mzegar.github.io/blob/master/LICENSE"
description = ""
homepage = "https://mzegar.github.io/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Matthew Zegar"
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
